--- # config

defaults:
    ip: "192.168.2.106"
    shell: /sbin/nologin

options:
    write_in_netposition: 0


vhosts:
  vhost:
    root: "/var/www/vhost/webtests/webtest.greendemo.local"
    user: 
      name: 'webtest.greendemo.local'
      samba: 'Greendemo_WebTest'
      group: 
        name: 'nginx'
        id: 45
      
